version: '3'

services:

   
   mysqlDB:
    image: intland/mysql:5.7.21
    container_name: mysql-rdbms
    environment:
        MYSQL_PASSWORD: pass
        MYSQL_DATABASE: codebeamer
        MYSQL_USER: user
    ports:
      - "3308:3306"
             
   consul: 
    image: "consul"
    container_name: "consul-service-discovery"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
      # environment:
      #   - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      #   - "CONSUL_BIND_INTERFACE=eth0"
      #   - "CONSUL_HTTP_ADDR=0.0.0.0"
    hostname: "consul"
    ports:
      - "8301:8301"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    # command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetPrivateIP }}'"
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetInterfaceIP \"eth0\" }}'" 
     
  
   jaeger:
    image: jaegertracing/all-in-one:1.3.0
    ports:
    - 127.0.0.1:5775:5775/udp # accept zipkin.thrift over compact thrift protocol
    - 127.0.0.1:6831:6831/udp # accept jaeger.thrift over compact thrift protocol
    - 127.0.0.1:6832:6832/udp # accept jaeger.thrift over binary thrift protocol
    - 127.0.0.1:5778:5778 # serve configs
    - 0.0.0.0:16686:16686 # serve frontend
    - 0.0.0.0:14268:14268 # accept jaeger.thrift directly from clients

   quote-service:
     container_name: quote-service
     build:
       context: .
       dockerfile: QuoteDockerfile
     image: quote-service:latest
     ports:
          - 50053:50053
     depends_on:
          - consul
          - jaeger
  
   portfolio-service:
     container_name: portfolio-service
     environment:
          -  CONSUL_HOST="consul"
          -  CONSUL_PORT=8500
          -  JAEGER_HOST="jaeger"
          -  JAEGER_PORT=14268
          -  MYSQL_HOST= mysqlDB
          -  MYSQL_PORT=3306
          -  SERVICE_PORT=9070
          -  GRPC_SERVICE_PORT=9080
          -  MYSQL_USER= root
          -  MYSQL_PASSWORD = password
          -  MYSQL_DB = codebeamer
          -  MYSQL_URL = mysql://user:pass@codebeamer:3308/codebeamer
     build:
       context: .
       dockerfile: PortfolioDockerfile
     image: portfolio-service:latest
     ports:
          - 9080:9080
          - 9070:9070
     depends_on:
          - consul
          - jaeger
          - mysqlDB
   
   account-service:
     container_name: account-service
     environment:
          -  CONSUL_HOST="consul"
          -  CONSUL_PORT=8500
          -  JAEGER_HOST="jaeger"
          -  JAEGER_PORT=14268
          -  SERVICE_PORT=1701
          -  GRPC_SERVICE_PORT=1701
          
     build:
       context: .
       dockerfile: AccountDockerfile
     image: account-service:latest
     ports:
          - 1701:1701
     depends_on:
          - consul
          - jaeger
         