// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tradeRule.proto

package tradeRule

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TradeType int32

const (
	TradeType_BUY  TradeType = 0
	TradeType_SELL TradeType = 1
)

var TradeType_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}

var TradeType_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x TradeType) String() string {
	return proto.EnumName(TradeType_name, int32(x))
}

func (TradeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_91541b48f87ca11f, []int{0}
}

type TradeRule struct {
	AcctNumber           string   `protobuf:"bytes,1,opt,name=acctNumber,proto3" json:"acctNumber,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SellPrice            float64  `protobuf:"fixed64,3,opt,name=sellPrice,proto3" json:"sellPrice,omitempty"`
	BuyPrice             float64  `protobuf:"fixed64,4,opt,name=buyPrice,proto3" json:"buyPrice,omitempty"`
	SellQuantity         int64    `protobuf:"varint,5,opt,name=sellQuantity,proto3" json:"sellQuantity,omitempty"`
	BuyQuantity          int64    `protobuf:"varint,6,opt,name=buyQuantity,proto3" json:"buyQuantity,omitempty"`
	TradeType            int32    `protobuf:"varint,7,opt,name=tradeType,proto3" json:"tradeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeRule) Reset()         { *m = TradeRule{} }
func (m *TradeRule) String() string { return proto.CompactTextString(m) }
func (*TradeRule) ProtoMessage()    {}
func (*TradeRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_91541b48f87ca11f, []int{0}
}

func (m *TradeRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRule.Unmarshal(m, b)
}
func (m *TradeRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRule.Marshal(b, m, deterministic)
}
func (m *TradeRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRule.Merge(m, src)
}
func (m *TradeRule) XXX_Size() int {
	return xxx_messageInfo_TradeRule.Size(m)
}
func (m *TradeRule) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRule.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRule proto.InternalMessageInfo

func (m *TradeRule) GetAcctNumber() string {
	if m != nil {
		return m.AcctNumber
	}
	return ""
}

func (m *TradeRule) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TradeRule) GetSellPrice() float64 {
	if m != nil {
		return m.SellPrice
	}
	return 0
}

func (m *TradeRule) GetBuyPrice() float64 {
	if m != nil {
		return m.BuyPrice
	}
	return 0
}

func (m *TradeRule) GetSellQuantity() int64 {
	if m != nil {
		return m.SellQuantity
	}
	return 0
}

func (m *TradeRule) GetBuyQuantity() int64 {
	if m != nil {
		return m.BuyQuantity
	}
	return 0
}

func (m *TradeRule) GetTradeType() int32 {
	if m != nil {
		return m.TradeType
	}
	return 0
}

type TradeRuleRequest struct {
	TradeRule            *TradeRule `protobuf:"bytes,1,opt,name=tradeRule,proto3" json:"tradeRule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TradeRuleRequest) Reset()         { *m = TradeRuleRequest{} }
func (m *TradeRuleRequest) String() string { return proto.CompactTextString(m) }
func (*TradeRuleRequest) ProtoMessage()    {}
func (*TradeRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91541b48f87ca11f, []int{1}
}

func (m *TradeRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRuleRequest.Unmarshal(m, b)
}
func (m *TradeRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRuleRequest.Marshal(b, m, deterministic)
}
func (m *TradeRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRuleRequest.Merge(m, src)
}
func (m *TradeRuleRequest) XXX_Size() int {
	return xxx_messageInfo_TradeRuleRequest.Size(m)
}
func (m *TradeRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRuleRequest proto.InternalMessageInfo

func (m *TradeRuleRequest) GetTradeRule() *TradeRule {
	if m != nil {
		return m.TradeRule
	}
	return nil
}

type TradeRulesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeRulesRequest) Reset()         { *m = TradeRulesRequest{} }
func (m *TradeRulesRequest) String() string { return proto.CompactTextString(m) }
func (*TradeRulesRequest) ProtoMessage()    {}
func (*TradeRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91541b48f87ca11f, []int{2}
}

func (m *TradeRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRulesRequest.Unmarshal(m, b)
}
func (m *TradeRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRulesRequest.Marshal(b, m, deterministic)
}
func (m *TradeRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRulesRequest.Merge(m, src)
}
func (m *TradeRulesRequest) XXX_Size() int {
	return xxx_messageInfo_TradeRulesRequest.Size(m)
}
func (m *TradeRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRulesRequest proto.InternalMessageInfo

type TradeRuleResponse struct {
	RuleNumber           string   `protobuf:"bytes,1,opt,name=ruleNumber,proto3" json:"ruleNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeRuleResponse) Reset()         { *m = TradeRuleResponse{} }
func (m *TradeRuleResponse) String() string { return proto.CompactTextString(m) }
func (*TradeRuleResponse) ProtoMessage()    {}
func (*TradeRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91541b48f87ca11f, []int{3}
}

func (m *TradeRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRuleResponse.Unmarshal(m, b)
}
func (m *TradeRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRuleResponse.Marshal(b, m, deterministic)
}
func (m *TradeRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRuleResponse.Merge(m, src)
}
func (m *TradeRuleResponse) XXX_Size() int {
	return xxx_messageInfo_TradeRuleResponse.Size(m)
}
func (m *TradeRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRuleResponse proto.InternalMessageInfo

func (m *TradeRuleResponse) GetRuleNumber() string {
	if m != nil {
		return m.RuleNumber
	}
	return ""
}

type TradeRulesResponse struct {
	TradeRules           []*TradeRule `protobuf:"bytes,1,rep,name=tradeRules,proto3" json:"tradeRules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TradeRulesResponse) Reset()         { *m = TradeRulesResponse{} }
func (m *TradeRulesResponse) String() string { return proto.CompactTextString(m) }
func (*TradeRulesResponse) ProtoMessage()    {}
func (*TradeRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91541b48f87ca11f, []int{4}
}

func (m *TradeRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRulesResponse.Unmarshal(m, b)
}
func (m *TradeRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRulesResponse.Marshal(b, m, deterministic)
}
func (m *TradeRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRulesResponse.Merge(m, src)
}
func (m *TradeRulesResponse) XXX_Size() int {
	return xxx_messageInfo_TradeRulesResponse.Size(m)
}
func (m *TradeRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRulesResponse proto.InternalMessageInfo

func (m *TradeRulesResponse) GetTradeRules() []*TradeRule {
	if m != nil {
		return m.TradeRules
	}
	return nil
}

func init() {
	proto.RegisterEnum("TradeType", TradeType_name, TradeType_value)
	proto.RegisterType((*TradeRule)(nil), "TradeRule")
	proto.RegisterType((*TradeRuleRequest)(nil), "TradeRuleRequest")
	proto.RegisterType((*TradeRulesRequest)(nil), "TradeRulesRequest")
	proto.RegisterType((*TradeRuleResponse)(nil), "TradeRuleResponse")
	proto.RegisterType((*TradeRulesResponse)(nil), "TradeRulesResponse")
}

func init() { proto.RegisterFile("tradeRule.proto", fileDescriptor_91541b48f87ca11f) }

var fileDescriptor_91541b48f87ca11f = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x6a, 0xf2, 0x40,
	0x14, 0xc5, 0xbf, 0xf9, 0xe2, 0xdf, 0x6b, 0x8b, 0x7a, 0x85, 0x12, 0xa4, 0x48, 0xc8, 0x2a, 0xb8,
	0xc8, 0x42, 0x37, 0x2e, 0xba, 0x28, 0x85, 0xee, 0xa4, 0xb4, 0xa3, 0x5d, 0x74, 0x69, 0xd2, 0x4b,
	0x11, 0x12, 0x93, 0x66, 0x66, 0x0a, 0x79, 0x84, 0x3e, 0x66, 0xdf, 0xa4, 0x64, 0x1a, 0x33, 0xa3,
	0x2e, 0xe7, 0x77, 0xce, 0x71, 0x3c, 0x67, 0x02, 0x43, 0x59, 0xec, 0xde, 0x89, 0xab, 0x84, 0xc2,
	0xbc, 0xc8, 0x64, 0xe6, 0xff, 0x30, 0xe8, 0x6f, 0x8f, 0x0c, 0x67, 0x00, 0xbb, 0x38, 0x96, 0x4f,
	0x2a, 0x8d, 0xa8, 0x70, 0x99, 0xc7, 0x82, 0x3e, 0xb7, 0x08, 0xde, 0x40, 0x47, 0x94, 0x69, 0x94,
	0x25, 0xee, 0x7f, 0xad, 0xd5, 0x27, 0xbc, 0x85, 0xbe, 0xa0, 0x24, 0x79, 0x2e, 0xf6, 0x31, 0xb9,
	0x8e, 0xc7, 0x02, 0xc6, 0x0d, 0xc0, 0x29, 0xf4, 0x22, 0x55, 0xfe, 0x89, 0x2d, 0x2d, 0x36, 0x67,
	0xf4, 0xe1, 0xaa, 0x32, 0xbe, 0xa8, 0xdd, 0x41, 0xee, 0x65, 0xe9, 0xb6, 0x3d, 0x16, 0x38, 0xfc,
	0x84, 0xa1, 0x07, 0x83, 0x48, 0x95, 0x8d, 0xa5, 0xa3, 0x2d, 0x36, 0xaa, 0xee, 0xd7, 0xc5, 0xb6,
	0x65, 0x4e, 0x6e, 0xd7, 0x63, 0x41, 0x9b, 0x1b, 0xe0, 0xdf, 0xc1, 0xa8, 0xa9, 0xc8, 0xe9, 0x53,
	0x91, 0x90, 0x18, 0xd4, 0x89, 0x8a, 0xe9, 0xa2, 0x83, 0x05, 0x84, 0xc6, 0x65, 0x44, 0x7f, 0x02,
	0xe3, 0x86, 0x8b, 0x3a, 0xee, 0x2f, 0x2d, 0xc8, 0x49, 0xe4, 0xd9, 0x41, 0xe8, 0xf5, 0x0a, 0x95,
	0xd0, 0xe9, 0x7a, 0x86, 0xf8, 0xf7, 0x80, 0xf6, 0x2f, 0xd5, 0xa9, 0x39, 0x40, 0x73, 0x99, 0x70,
	0x99, 0xe7, 0x9c, 0xfd, 0x15, 0x4b, 0x9d, 0xcf, 0xea, 0xc7, 0xaa, 0x6a, 0x61, 0x17, 0x9c, 0x87,
	0xd7, 0xb7, 0xd1, 0x3f, 0xec, 0x41, 0x6b, 0xf3, 0xb8, 0x5e, 0x8f, 0xd8, 0xe2, 0x9b, 0xc1, 0xc4,
	0x24, 0xf3, 0x78, 0x43, 0xc5, 0x57, 0xb5, 0xf2, 0x0a, 0x86, 0x42, 0x45, 0xe9, 0x5e, 0x9a, 0xa7,
	0x1e, 0x87, 0xe7, 0x9b, 0x4c, 0x31, 0xbc, 0xec, 0xb4, 0x82, 0xeb, 0x0f, 0x32, 0x31, 0x81, 0x96,
	0xe9, 0xb8, 0xc6, 0x74, 0x12, 0x5e, 0xf6, 0x8a, 0x3a, 0xfa, 0x03, 0x5b, 0xfe, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xee, 0xa6, 0xea, 0xd0, 0x73, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TradeRuleRpcServiceClient is the client API for TradeRuleRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradeRuleRpcServiceClient interface {
	SubmitTradeRule(ctx context.Context, in *TradeRuleRequest, opts ...grpc.CallOption) (*TradeRuleResponse, error)
	GetTradeRules(ctx context.Context, in *TradeRulesRequest, opts ...grpc.CallOption) (*TradeRulesResponse, error)
}

type tradeRuleRpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewTradeRuleRpcServiceClient(cc *grpc.ClientConn) TradeRuleRpcServiceClient {
	return &tradeRuleRpcServiceClient{cc}
}

func (c *tradeRuleRpcServiceClient) SubmitTradeRule(ctx context.Context, in *TradeRuleRequest, opts ...grpc.CallOption) (*TradeRuleResponse, error) {
	out := new(TradeRuleResponse)
	err := c.cc.Invoke(ctx, "/TradeRuleRpcService/submitTradeRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeRuleRpcServiceClient) GetTradeRules(ctx context.Context, in *TradeRulesRequest, opts ...grpc.CallOption) (*TradeRulesResponse, error) {
	out := new(TradeRulesResponse)
	err := c.cc.Invoke(ctx, "/TradeRuleRpcService/getTradeRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeRuleRpcServiceServer is the server API for TradeRuleRpcService service.
type TradeRuleRpcServiceServer interface {
	SubmitTradeRule(context.Context, *TradeRuleRequest) (*TradeRuleResponse, error)
	GetTradeRules(context.Context, *TradeRulesRequest) (*TradeRulesResponse, error)
}

// UnimplementedTradeRuleRpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTradeRuleRpcServiceServer struct {
}

func (*UnimplementedTradeRuleRpcServiceServer) SubmitTradeRule(ctx context.Context, req *TradeRuleRequest) (*TradeRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTradeRule not implemented")
}
func (*UnimplementedTradeRuleRpcServiceServer) GetTradeRules(ctx context.Context, req *TradeRulesRequest) (*TradeRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTradeRules not implemented")
}

func RegisterTradeRuleRpcServiceServer(s *grpc.Server, srv TradeRuleRpcServiceServer) {
	s.RegisterService(&_TradeRuleRpcService_serviceDesc, srv)
}

func _TradeRuleRpcService_SubmitTradeRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeRuleRpcServiceServer).SubmitTradeRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TradeRuleRpcService/SubmitTradeRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeRuleRpcServiceServer).SubmitTradeRule(ctx, req.(*TradeRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeRuleRpcService_GetTradeRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeRuleRpcServiceServer).GetTradeRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TradeRuleRpcService/GetTradeRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeRuleRpcServiceServer).GetTradeRules(ctx, req.(*TradeRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TradeRuleRpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TradeRuleRpcService",
	HandlerType: (*TradeRuleRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "submitTradeRule",
			Handler:    _TradeRuleRpcService_SubmitTradeRule_Handler,
		},
		{
			MethodName: "getTradeRules",
			Handler:    _TradeRuleRpcService_GetTradeRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradeRule.proto",
}
